### ISSUE TITLE
discarding hand with enchanted cards errors

### ISSUE THREAD

**Issue by hstoner009** [jleclanche/fireplace#58] opened 2015-06-06 03:40 UTC
Hey,

I think when discard is called on the hand, if the card is buffed by an enchantment like Thaurissan (buff="BRM_028e"), I hit this error:

AttributeError: 'Enchantment' object has no attribute 'discard'

Temporarily I just added a discard for enchantments and call destroy from it but if there's a better solution let me know.

**Comment by jleclanche** [comment] 2015-06-06 07:51
Can't repro:

https://github.com/jleclanche/fireplace/commit/76ff26d9d3d670074ca292809b1ddeb33aee3c92

**Comment by jleclanche** [comment] 2015-06-06 07:54
Can't repro with discardHand() either. Note that it makes no sense discard would be called on the buffs. All discard does is move to the GRAVEYARD zone...

**Comment by hstoner009** [comment] 2015-06-06 13:35
Sorry for the mistake! I think I may have misused your buffing mechanic. 

        buff = game.player1.give('GVG_003e')
        buff.buff(game.player1.hand[0],'GVG_003e')

I was generating buffs this way, but I think the give puts the buff in the hand...so it was being discarded. Instead, I think this might be a safer way to buff... game.player1.hero.buff(crd, buff_id)?

**Comment by jleclanche** [comment] 2015-06-06 13:38
Ok, I'll keep the test but this is good to know.

**Comment by jleclanche** [comment] 2015-07-01 03:54
I just realized I haven't implemented thaurissan, which would explain why I can't repro >.>.

**Comment by jleclanche** [comment] 2015-07-12 13:56
I have now implemented thaurissan in 0b0a19317d7faf19ce0fcbda7500cf74d536176 and I still can't reproduce. Closing.

**Closed by jleclanche** 2015-07-12 13:56 UTC

**Comment by hstoner009** [comment] 2015-07-12 14:32
Oh sorry for the late reply. There was no issue, instead I was incorrectly using your buff mechanic by creating a buff card in my hand and then buffing. This causes discard to be called on a buff. I think we discussed this a month ago over irc.

**Comment by jleclanche** [comment] 2015-07-12 14:35
Ah, yeah. I remember now. Anyway, thaurissan done ;)

PS: The channel's growing, stick around? :P
