### ISSUE TITLE
Blackwing Technician Error

### ISSUE THREAD

**Issue by hstoner009** [jleclanche/fireplace#102] opened 2015-08-07 02:30 UTC
Hello,

Tested summoning a blackwing technician and arrived at the following error:

  File "C:\Python34\lib\site-packages\fireplace-0.1-py3.4.egg\fireplace\actions.py", line 231, in do
    card.action()
  File "C:\Python34\lib\site-packages\fireplace-0.1-py3.4.egg\fireplace\card.py", line 224, in action
    self.game.queue_actions(self, actions)
  File "C:\Python34\lib\site-packages\fireplace-0.1-py3.4.egg\fireplace\game.py", line 202, in queue_actions
    ret.append(action.trigger(source))
  File "C:\Python34\lib\site-packages\fireplace-0.1-py3.4.egg\fireplace\dsl\evaluator.py", line 36, in trigger
    action.trigger(source)
  File "C:\Python34\lib\site-packages\fireplace-0.1-py3.4.egg\fireplace\actions.py", line 314, in trigger
    ret.append(self.do(source, target, *target_args))
  File "C:\Python34\lib\site-packages\fireplace-0.1-py3.4.egg\fireplace\actions.py", line 490, in do
    attack_source.hit(target, amount)
  File "C:\Python34\lib\site-packages\fireplace-0.1-py3.4.egg\fireplace\card.py", line 583, in hit
    super().hit(target, amount)
  File "C:\Python34\lib\site-packages\fireplace-0.1-py3.4.egg\fireplace\card.py", line 274, in hit
    return self.game.queue_actions(self, [Damage(target, amount)])
  File "C:\Python34\lib\site-packages\fireplace-0.1-py3.4.egg\fireplace\game.py", line 202, in queue_actions
    ret.append(action.trigger(source))
  File "C:\Python34\lib\site-packages\fireplace-0.1-py3.4.egg\fireplace\actions.py", line 308, in trigger
    targets = self.get_targets(source, args[0])
  File "C:\Python34\lib\site-packages\fireplace-0.1-py3.4.egg\fireplace\actions.py", line 298, in get_targets
    return t.eval(source.game, source)
AttributeError: 'NoneType' object has no attribute 'eval'

This was the test case that I was using.

    dragon = game.player1.give("BRM_004")
    blackwing = game.player1.give("BRM_033")
    blackwing.play()

**Comment by hstoner009** [comment] 2015-08-07 02:39
just saw the bug post, you can disregard, my apologies

**Comment by jleclanche** [comment] 2015-08-07 03:17
Yeah dupe of #99

**Closed by jleclanche** 2015-08-07 03:17 UTC

**Comment by jleclanche** [comment] 2015-08-07 04:11
@hstoner009 fixed in c723eb99a77be62f269f13eaaf8d39f19931df94
