### ISSUE TITLE
issue with adjacent minions

### ISSUE THREAD

**Issue by hstoner009** [jleclanche/fireplace#28] opened 2015-04-08 01:15 UTC
Hey,

I'll look into joining the irc channel. I was running the following test and hit "AssertionError: Zone.GRAVEYARD". The error looks like it has to do with the zone assertion in the adjacentMinions function.

    game = prepare_game()
    dire1 = game.player1.give("EX1_162")
    dire2 = game.player1.give("EX1_162")
    dire1.play()
    dire2.play()
    game.endTurn();
    yeti = game.player2.give("GVG_078")
    yeti.play()
    yeti.attack(dire2)

Interestingly enough, if the yeti attack dire1, the assert is not triggered.

**Comment by jleclanche** [comment] 2015-04-08 01:49
Thanks. I'm currently doing a pretty massive revamp of the tag system so this one will have to wait until  that's done.

**Comment by hstoner009** [comment] 2015-04-08 01:55
No problem! If I am bombarding you too frequently with these issues, let me know and I can try to queue up more issues that I observe before I pass them along to you.

**Comment by jleclanche** [comment] 2015-04-08 01:58
No don't worry, file as much as you want, I appreciate it a lot. It helps having someone test stuff for actual situations. =)

But yeah if you have anything immediate, swing by the IRC channel instead. You can try [Freenode's Webchat](https://webchat.freenode.net/) if you don't have an IRC client.

**Comment by jleclanche** [comment] 2015-04-09 06:09
Phew, done with the tag refactoring.

This is an interesting bug for sure. The true root cause is my lack of support for a "death phase". Deaths currently happen instantaneously.

What this means in practice is that when the yeti hits the wolf, the DAMAGE event is broadcast. That DAMAGE event is what causes the wolf to die, and it is moved to the graveyard during event propagation. During said DAMAGE broadcast, the UPDATE event is re-broadcast all the time to those same entities, and towards the end of the propagation chain is the Aura, which has already been destroyed and whose source is already in the graveyard, but it's still in the event listener.

A real fix for this won't come until I implement the death phase, but I'll see if I can fix it some other way.

**Comment by jleclanche** [comment] 2015-05-05 16:06
Fixed by the new actions API, which includes proper death events :)

**Closed** 2015-05-05 16:06 UTC
